/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package batallanaval;

import java.awt.MouseInfo;
import java.awt.Point;

/**
 *
 * @author winstonjgz
 */
public class Tablero extends javax.swing.JFrame {
int varX = 70;
int varY = 80;
    public Tablero() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Barco1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        txtY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(212, 208, 86));
        jPanel1.setMinimumSize(new java.awt.Dimension(1500, 500));
        jPanel1.setLayout(null);

        Barco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco1.png"))); // NOI18N
        Barco1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Barco1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barco1MouseDragged(evt);
            }
        });
        jPanel1.add(Barco1);
        Barco1.setBounds(33, 31, 144, 63);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco2.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(226, 32, 116, 62);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agua.PNG"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(393, 100, 725, 590);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco4.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(226, 175, 87, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco3.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(33, 148, 104, 87);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco5.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(33, 313, 87, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco7.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(33, 430, 224, 65);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco6.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(226, 313, 137, 65);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco8.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(33, 541, 102, 70);

        jLabel10.setText("Jugador activo:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(450, 40, 130, 17);
        jPanel1.add(lblUsuario);
        lblUsuario.setBounds(570, 30, 130, 30);
        jPanel1.add(txtX);
        txtX.setBounds(1086, 20, 110, 27);
        jPanel1.add(txtY);
        txtY.setBounds(1210, 20, 100, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Barco1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barco1MouseDragged
        Point punto = MouseInfo.getPointerInfo().getLocation();
        this.Barco1.setLocation(punto.x-varX, punto.y-varY);
        
        this.txtX.setText(String.valueOf(punto.x));
        this.txtY.setText(String.valueOf(punto.y));
      
        
        
    }//GEN-LAST:event_Barco1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barco1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    // End of variables declaration//GEN-END:variables
}
